### PR TITLE
Add mbed-simulator support

### PR DESCRIPTION
**Pull request by janjongboom**
WIP, probably don't merge until the new mbed-simulator branch is merged.

To run:

1. Install the latest [mbed-simulator](https://github.com/janjongboom/mbed-simulator/tree/fix-cli) repository.
2. Run `mbed-simulator -i . -o BUILD/SIMULATOR/ --launch`
3. Add the touch screen component.

Now the MNIST demo runs in your browser.

### CODE REVIEW

**Comment by neil-tan** [comment]
@dboyliao   I'll be testing this, but feel free to try it out.

**Comment by mbartling** [comment]
@neil-tan do you still have time for this?

**Comment by janjongboom** [comment]
@mbartling @neil-tan I need to fix some stuff in the simulator still.

**Comment by janjongboom** [comment]
@neil-tan You can now run:

```
$ npm install mbed-simulator -g
```

And then run the simulator in this project via;

```
$ mbed-simulator .
```

**Pull request merged**
